routes/admin.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/ssss', function () {
    return view('welcome');
});
///////////////////////////////////////////Logout Admin ///////////////////////////////////////////
Route::get('logout' ,function (){
    Auth::guard('admin')->logout();
    return redirect()->route('get.admin.login');
} )->name('admin-logout');
/////////////////////////////////////////End logout//////////////////////////////////////////////

Route::group(['namespace'=>'App\Http\Controllers\Admin','middleware'=>'auth:admin','name'=>'.dashboard'],function () {
    Route::group(['prefix'=>'dashboard'],function () {
        Route::get('/', 'DashboardController@index')->name('dashboard.index');
        /////////////////////////////Start Category//////////////////////////////////////
        Route::resource('category', 'CategoryController')->except(['show']);
        /////////////////////////////End Category//////////////////////////////////////

        /////////////////////////////Start Book//////////////////////////////////////
        Route::resource('book', 'BookController')->except(['show']);
        Route::get('/founded/{ID}','BookController@changeStatus')->name('book.status');
        Route::get('studentBorrowBook/{id}', 'BookController@studentRequest')->name('student-borrow');

        /////////////////////////////End Book//////////////////////////////////////
        /////////////////////////////Start Student//////////////////////////////////////
         Route::resource('student', 'StudentController')->except(['show','create','edit','update','story']);
         Route::get('booksRequest/{id}', 'StudentController@bookRequest')->name('books-request');
        /////////////////////////////End Student//////////////////////////////////////
        /////////////////////////////Start Borrow Request/////////////////////////////////////
         Route::resource('borrowRequest', 'BorrowRequestController')->except(['show','create','edit','update','story']);
        Route::get('/accept/{ID}','BorrowRequestController@changeAccept')->name('borrow.accept');
        Route::get('/Roof/{ID}','BorrowRequestController@changeRoof')->name('roof.found');
        /////////////////////////////End BorrowRequest//////////////////////////////////////

        /// //////////////////////////// change pass//////////////////////////////////////
        Route::get('changePassword','ChangePassController@change')->name('admin.change');
        Route::post('changePassword','ChangePassController@updateChange')->name('admin.update.change');
        /// //////////////////////////// End Pass   /////////////////////////////////////

    });



});
Route::group(['namespace'=>'App\Http\Controllers\Admin\Auth','middleware'=>'guest:admin'],function (){
    Route::get('login','LoginController@getLogin')->name('get.admin.login');
    Route::post('login','LoginController@Login')->name('admin.login');

});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('logout' ,function (){
    Auth::logout();
    return redirect()->route('get.front.login');
} )->name('client-logout');

Route::group(['namespace'=>'App\Http\Controllers\Front','middleware'=>'auth:web'],function () {
    Route::get('booksDet', 'MainController@books')->name('books');
    Route::get('detailsBook/{id}', 'MainController@booksDetails')->name('details-books');
    Route::get('borrowRequest/{id}', 'MainController@borrow_request')->name('borrow-request');
    Route::post('pushBorrow', 'MainController@pushBorrow')->name('push-borrow-request');
    Route::get('borrowRequest', 'MainController@student_borrow_request')->name('student-borrow-request');
    Route::get('profile' , 'MainController@getProfile')->name('get.student.profile');
    Route::post('editProfile' , 'MainController@editProfile')->name('edit.student.profile');
    Route::get('getEditPass' , 'MainController@getEdtPass')->name('get.student.EditPass');
    Route::post('editPass' , 'MainController@editPass')->name('edit.student.Pass');
    Route::get('contact' , 'MainController@getContact')->name('contact.me');



});
Route::group(['namespace'=>'App\Http\Controllers\Front'],function (){
    Route::get('logins','LoginController@getClientLogin')->name('get.front.login');
    Route::post('logins','LoginController@Login')->name('front.login');
    Route::get('registers','RegisterController@getClientRegister')->name('get.front.register');
    Route::post('registers','RegisterController@Register')->name('front.register');
    Route::get('/home', 'MainController@home')->name('client-home');
    Route::get('about-us', 'MainController@about')->name('about.us');


});
/*Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');*/

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $fillable=['id','name'];
    public function books(){
        return $this ->hasMany('App\Models\Book');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\CategoryRequest;
use App\Models\Category;
use App\Traits\GeneralTrait;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function index()
    {
      $categories=Category::all();
      return view('admin.category.index',compact('categories'));
    }


    public function create()
    {
        return view('admin.category.create');
    }


    public function store(CategoryRequest $request)
    {
        try {
            $categories = Category::create($request->all());
            return redirect()->route('category.index')->with(['success' => 'Successfully Added']);
        } catch (\Exception $ex){
            return redirect()->route('category.index')->with(['error' => 'Sorry Something went wrong']);

        }
    }



    public function edit($id)
    {
      $categories=Category::findOrFail($id);
      if(!$categories){
          return redirect()->route('category.index')->with(['error' => 'Sorry This item Not Found']);
      }
      return view('admin.category.edit',compact('categories'));
    }


    public function update(CategoryRequest $request, $id)
    {
        try {
            $categories=Category::findOrFail($id);
            if(!$categories){
                return redirect()->route('category.index')->with(['error' => 'Sorry This item Not Found']);
            }
            $categories->update($request->all());
            return redirect()->route('category.index')->with(['success' => 'Successfully Edit']);

        }catch (\Exception $ex){
            return redirect()->route('category.index')->with(['error' => 'Sorry Something went wrong']);
        }
    }


    public function destroy($id)
    {
        try {
            $categories=Category::findOrFail($id);
            if(!$categories){
                return redirect()->route('category.index')->with(['error' => 'Sorry This item Not Found']);
            }
            $categories->delete();
            return redirect()->route('category.index')->with(['success' => 'Successfully Deleted']);

        }catch (\Exception $ex){
            return redirect()->route('category.index')->with(['error' => 'Sorry Something went wrong']);

        }
    }
}

resources/views/admin/category/create.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">  Add Category </h6> <br>
                </div>
            </div>
            <div class="box-body">
                @include('admin.include.alerts.errors')
                @include('admin.include.alerts.success')
                <div class="card-body">
                    <form action="{{route('category.store')}}" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="col-md-12">
                            <div class="form-group">
                                <label> Name Of Category </label>
                                <input class="form-control" type="text" name="name" value="{{old('name')}}">
                                @error("name")
                                <span class="text-danger">{{$message}} </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <button class="btn btn-primary btn-icon-split" type="submit" >
                                    <span class="icon text-white-50"><i class="fas fa-plus"></i>
                                    </span>
                                    <span class="text"> Add Category</span>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>{{--end box body--}}
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/admin/category/edit.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">  Edit Category </h6> <br>
                </div>
            </div>
            <div class="box-body">
                @include('admin.include.alerts.errors')
                @include('admin.include.alerts.success')
                <div class="card-body">
                    <form action="{{route('category.update',$categories->id)}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('put')
                        <input type="hidden" name="id" value="{{$categories->id}}"> {{-- عشان الصوره لو محبتش اغيرها --}}

                        <div class="col-md-12">
                            <div class="form-group">
                                <label> Name Of Category </label>
                                <input class="form-control" type="text" name="name" value="{{$categories->name}}">
                                @error("name")
                                <span class="text-danger">{{$message}} </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <button class="btn btn-primary btn-icon-split" type="submit" >
                                    <span class="icon text-white-50"><i class="fas fa-plus"></i>
                                    </span>
                                    <span class="text"> Edit Category</span>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>{{--end box body--}}
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/admin/category/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="container-fluid">

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">   Category <small style="color:black;">{{$categories -> count()}}</small></h6>  <br>
                @include('admin.include.alerts.errors')
                @include('admin.include.alerts.success')
                <form action="" method="get">
                    @csrf
                    <div class="row">
                        <div class="col-md-4">
                            <input type="text" name="search" class="form-control" placeholder="search" value="" >
                        </div>
                        <div class="col-md-4">
                            <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i> search</button>

                            <a class="btn btn-primary btn-icon-split " href="{{route('category.create')}}"><span class="icon text-white-50"><i class="fas fa-plus"></i>
                                    </span>
                                <span class="text"> Add </span></a>

                        </div>

                    </div> {{-- end  row--}}

                </form> {{-- end form --}}

            </div>

            <div class="card-body">


                <div class="table-responsive">
                    @if(isset($categories)&&count($categories))
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Category Name</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>

                            @foreach($categories as $index=> $category)

                            <td>{{$index +1 }}</td>
                            <td>{{$category ->name}}</td>
                            <td>
                                <a href="{{route('category.edit',$category->id)}}" class="btn btn-primary btn-circle btn-lg"><i class="fas fa-info-circle"></i></a>
                            </td>

                                <td>

                                    <form action="{{route('category.destroy',$category->id)}}" method="post" >
                                        {{csrf_field()}}
                                        {{method_field('delete')}}

                                        <button type="submit" class="btn btn-danger btn-circle btn-lg"> <i class="fas fa-trash"></i>
                                        </button>
                                    </form>

                                </td>
                        </tr>


                        @endforeach

                        </tbody>
                    </table>
                    @else
                        <h2>data not found</h2>
                    @endif
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@endsection