routes/admin.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/ssss', function () {
    return view('welcome');
});
///////////////////////////////////////////Logout Admin ///////////////////////////////////////////
Route::get('logout' ,function (){
    Auth::guard('admin')->logout();
    return redirect()->route('get.admin.login');
} )->name('admin-logout');
/////////////////////////////////////////End logout//////////////////////////////////////////////

Route::group(['namespace'=>'App\Http\Controllers\Admin','middleware'=>'auth:admin','name'=>'.dashboard'],function () {
    Route::group(['prefix'=>'dashboard'],function () {
        Route::get('/', 'DashboardController@index')->name('dashboard.index');
        /////////////////////////////Start Category//////////////////////////////////////
        Route::resource('category', 'CategoryController')->except(['show']);
        /////////////////////////////End Category//////////////////////////////////////

        /////////////////////////////Start Book//////////////////////////////////////
        Route::resource('book', 'BookController')->except(['show']);
        Route::get('/founded/{ID}','BookController@changeStatus')->name('book.status');
        Route::get('studentBorrowBook/{id}', 'BookController@studentRequest')->name('student-borrow');

        /////////////////////////////End Book//////////////////////////////////////
        /////////////////////////////Start Student//////////////////////////////////////
         Route::resource('student', 'StudentController')->except(['show','create','edit','update','story']);
         Route::get('booksRequest/{id}', 'StudentController@bookRequest')->name('books-request');
        /////////////////////////////End Student//////////////////////////////////////
        /////////////////////////////Start Borrow Request/////////////////////////////////////
         Route::resource('borrowRequest', 'BorrowRequestController')->except(['show','create','edit','update','story']);
        Route::get('/accept/{ID}','BorrowRequestController@changeAccept')->name('borrow.accept');
        Route::get('/Roof/{ID}','BorrowRequestController@changeRoof')->name('roof.found');
        /////////////////////////////End BorrowRequest//////////////////////////////////////

        /// //////////////////////////// change pass//////////////////////////////////////
        Route::get('changePassword','ChangePassController@change')->name('admin.change');
        Route::post('changePassword','ChangePassController@updateChange')->name('admin.update.change');
        /// //////////////////////////// End Pass   /////////////////////////////////////

    });



});
Route::group(['namespace'=>'App\Http\Controllers\Admin\Auth','middleware'=>'guest:admin'],function (){
    Route::get('login','LoginController@getLogin')->name('get.admin.login');
    Route::post('login','LoginController@Login')->name('admin.login');

});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('logout' ,function (){
    Auth::logout();
    return redirect()->route('get.front.login');
} )->name('client-logout');

Route::group(['namespace'=>'App\Http\Controllers\Front','middleware'=>'auth:web'],function () {
    Route::get('booksDet', 'MainController@books')->name('books');
    Route::get('detailsBook/{id}', 'MainController@booksDetails')->name('details-books');
    Route::get('borrowRequest/{id}', 'MainController@borrow_request')->name('borrow-request');
    Route::post('pushBorrow', 'MainController@pushBorrow')->name('push-borrow-request');
    Route::get('borrowRequest', 'MainController@student_borrow_request')->name('student-borrow-request');
    Route::get('profile' , 'MainController@getProfile')->name('get.student.profile');
    Route::post('editProfile' , 'MainController@editProfile')->name('edit.student.profile');
    Route::get('getEditPass' , 'MainController@getEdtPass')->name('get.student.EditPass');
    Route::post('editPass' , 'MainController@editPass')->name('edit.student.Pass');
    Route::get('contact' , 'MainController@getContact')->name('contact.me');



});
Route::group(['namespace'=>'App\Http\Controllers\Front'],function (){
    Route::get('logins','LoginController@getClientLogin')->name('get.front.login');
    Route::post('logins','LoginController@Login')->name('front.login');
    Route::get('registers','RegisterController@getClientRegister')->name('get.front.register');
    Route::post('registers','RegisterController@Register')->name('front.register');
    Route::get('/home', 'MainController@home')->name('client-home');
    Route::get('about-us', 'MainController@about')->name('about.us');


});
/*Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');*/

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use function PHPUnit\Framework\assertGreaterThan;

class Book extends Model
{
    use HasFactory;
    protected $fillable=['id','name','title','photo','found','description','category_id','user_id'];
    public function category(){
        return $this ->belongsTo('App\Models\Category');
    }

    public function borrowRequests(){
        return $this->hasMany('App\Models\BorrowRequest');
    }

    public function getFound(){
        return $this->found==1?"Founded":"Not Founded";
    }
    public function getPhotoAttribute($q){
        return ($q!==null)?asset('assests/images/books/'.$q):"";
    }

}

app/Http/Controllers/Admin/BookController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\BookRequest;
use App\Models\Book;
use App\Traits\General;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class BookController extends Controller
{
    use General;


    public function index(Request $request)
    {
        $books=Book::where(function ($q) use($request){
            if($request->input('search')||$request->input('category_id')){
                return $q ->where('name','like','%'.$request->search.'%')->orwhere('category_id',$request->category_id);
            }})->get();;
        return view('admin.book.index',compact('books'));
    }

    public function create()
    {
       return view('admin.book.create');
    }

    public function store(BookRequest $request)
    {
        try {
            if (!$request->has('found')) {
                $request->request->add(['found' => 0]);
            } else {
                $request->request->add(['found' => 1]);
            }
            $path='';
            if($request->has('photo')){
                $path=$this->SaveImages($request->photo,'assests/images/books');
            }
            $request_data=$request->except(['photo']);
            $request_data['photo']=$path;

            $books=Book::create($request_data);
            return redirect()->route('book.index')->with(['success'=>"Add Successfully"]);
        }catch (\Exception $ex){
            return redirect()->route('book.index')->with(['error' => 'Sorry Something went wrong']);
        }

    }

    public function edit($id)
    {
        try {
            $books=Book::findOrFail($id);
            if (!$books){
                return redirect()->route('book.index')->with(['error' => 'Sorry This item Not Found']);
            }
            return view('admin.book.edit',compact('books'));
        }catch (\Exception $ex){
            return redirect()->route('book.index')->with(['error' => 'Sorry Something went wrong']);
        }

    }

    public function update(BookRequest $request, $id)
    {
        try {
            $books=Book::findOrFail($id);
            if (!$books){
                return redirect()->route('book.index')->with(['error' => 'Sorry This item Not Found']);
            }
            if (!$request->has('found')) {
                $request->request->add(['found' => 0]);
            } else {
                $request->request->add(['found' => 1]);
            }
            DB::beginTransaction();
            if($request ->has('photo')){
                $path=$this->SaveImages($request->photo,'assests/images/books');
                Book::where('id',$id)->update(['photo'=>$path]);
            }

            Book::where('id',$id)->update([
                'name'=>$request->name,
                'title'=>$request->title,
                'description'=>$request->description,
                'category_id'=>$request->category_id,
                'found'=>$request->found
            ]);
            DB::commit();
            return redirect()->route('book.index')->with(['success'=>"Edit Successfully"]);
        }catch (\Exception $ex){
            DB::rollBack();
            return redirect()->route('book.index')->with(['error' => 'Sorry Something went wrong']);
        }
    }

    public function destroy($id)
    {
        try {
            $books=Book::findOrFail($id);
            if(!$books){
                return redirect()->route('book.index')->with(['error' => 'Sorry This item Not Found']);
            }
            $photo=Str::after($books->photo,'assests/');
             $photo=base_path('public/assests/'.$photo);
            unlink($photo);
            $books->delete();

            return redirect()->route('book.index')->with(['success'=>"Delete Successfully"]);
        }catch (\Exception $ex){
            return redirect()->route('book.index')->with(['error' => 'Sorry Something went wrong']);
        }
    }
    public function changeStatus($ID)
    {
        try {
            $books=Book::findOrFail($ID);
            if (!$books){
                return redirect()->route('book.index')->with(['error' => 'Sorry This item Not Found']);
            }
            if($books->found == 1){
                $books->update([
                   'found'=>0
               ]);

                return redirect()->route('book.index')->with(['success'=>"Change Successfully"]);
            }
            if($books->found == 0){
                $books->update([
                    'found'=>1
                ]);
                return redirect()->route('book.index')->with(['success'=>"Change Successfully"]);
            }

        }catch (\Exception $ex){
            return redirect()->route('book.index')->with(['error' => 'Sorry Something went wrong']);
        }
    }
    public function studentRequest($id){
        $book=Book::findOrFail($id);
        $books=$book->borrowRequests;
        return view('admin.book.showStudentReq',compact('books'));
    }
}

resources/views/admin/book/create.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">  Add Book </h6> <br>
                </div>
            </div>
            <div class="box-body">
                @include('admin.include.alerts.errors')
                @include('admin.include.alerts.success')
                <div class="card-body">
                    <form action="{{route('book.store')}}" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="col-md-12">
                            <div class="form-group">
                                <label> Photo </label>
                                <input class="form-control" type="file" name="photo" value="{{old('photo')}}">
                                @error("photo")
                                <span class="text-danger">{{$message}} </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label> Name Of Book </label>
                                <input class="form-control" type="text" name="name" value="{{old('name')}}">
                                @error("name")
                                <span class="text-danger">{{$message}} </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label> Title Of Book </label>
                                <input class="form-control" type="text" name="title" value="{{old('title')}}">
                                @error("title")
                                <span class="text-danger">{{$message}} </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label> Description Of Book </label>
                                <textarea name="description" id="" cols="30" rows="10" class="form-control"></textarea>
                                @error("description")
                                <span class="text-danger">{{$message}} </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="form-check">
                                    <input type="checkbox" value="1" class="form-check-input" id="materialIndeterminate2" name="found" checked>
                                    <label class="form-check-label" for="materialIndeterminate2">Status</label>
                                </div>
                                @error("found")
                                <span class="text-danger">{{$message}} </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label> Select Of Category </label>
                                <select class="form-control" name="category_id">
                                    <optgroup label="Please choose Category To search"></optgroup>
                                    <option class="hidden">-----</option>
                                    @inject('categories','App\Models\Category')
                                    @foreach($categories ->all() as $category)
                                        <option value="{{ $category->id}}">
                                            {{$category ->name}}
                                        </option>
                                    @endforeach
                                </select>
                                @error("category_id")
                                <span class="text-danger">{{$message}} </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <button class="btn btn-primary btn-icon-split" type="submit" >
                                    <span class="icon text-white-50"><i class="fas fa-plus"></i>
                                    </span>
                                    <span class="text"> Add Book</span>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>{{--end box body--}}
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/admin/book/edit.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">  Edit Book </h6> <br>
                </div>
            </div>
            <div class="box-body">
                @include('admin.include.alerts.errors')
                @include('admin.include.alerts.success')
                <div class="card-body">
                    <form action="{{route('book.update',$books->id)}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('put')
                        <input type="hidden" name="id" value="{{$books->id}}"> {{-- عشان الصوره لو محبتش اغيرها --}}
                        <div class="col-md-12">
                            <div class="form-group">
                                <label> Photo </label>
                                <input class="form-control" type="file" name="photo" value="{{$books->photo}}">
                                @error("photo")
                                <span class="text-danger">{{$message}} </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label> Name Of Book </label>
                                <input class="form-control" type="text" name="name" value="{{$books->name}}">
                                @error("name")
                                <span class="text-danger">{{$message}} </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label> Title Of Book </label>
                                <input class="form-control" type="text" name="title" value="{{$books->title}}">
                                @error("title")
                                <span class="text-danger">{{$message}} </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label> Description Of Book </label>
                                <textarea name="description" id="" cols="30" rows="10" class="form-control">{{$books->description}}</textarea>
                                @error("description")
                                <span class="text-danger">{{$message}} </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="form-check">
                                    <input type="checkbox" value="1" class="form-check-input" id="materialIndeterminate2" name="found" @if($books->found==1)
                                    checked @endif>
                                    <label class="form-check-label" for="materialIndeterminate2">Status</label>
                                </div>
                                @error("found")
                                <span class="text-danger">{{$message}} </span>
                                @enderror
                            </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label> Select Of Category </label>
                                <select class="form-control" name="category_id">
                                    <optgroup label="Please choose Category To search"></optgroup>
                                    <option class="hidden">-----</option>
                                    @inject('categories','App\Models\Category')
                                    @foreach($categories->all() as $category)
                                        <option value="{{$category->id}}" @if($category->id == $books->category_id ) selected @endif>{{$category->name}}</option>
                                    @endforeach
                                </select>
                                @error("category_id")
                                <span class="text-danger">{{$message}} </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <button class="btn btn-primary btn-icon-split" type="submit" >
                                    <span class="icon text-white-50"><i class="fas fa-plus"></i>
                                    </span>
                                    <span class="text"> Add Book</span>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>{{--end box body--}}
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/admin/book/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="container-fluid">

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">  Books <small style="color:black;">{{$books -> count()}}</small></h6>  <br>
                @include('admin.include.alerts.errors')
                @include('admin.include.alerts.success')
                <form action="" method="get">
                    @csrf
                    <div class="row">
                        <div class="col-md-4">
                            <input type="text" name="search" class="form-control" placeholder="search" value="" >
                        </div>
                        <div class="col-md-4">
                            <select class="form-control" name="category_id">
                                <optgroup label="Please choose Category To search"></optgroup>
                                <option class="hidden">-----</option>
                                @inject('categories','App\Models\Category')
                                @foreach($categories ->all() as $category)
                                    <option value="{{ $category->id}}">
                                        {{$category ->name}}
                                    </option>
                                @endforeach
                            </select>
                        </div>

                        <div class="col-md-4">
                            <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i> search</button>

                            <a class="btn btn-primary btn-icon-split " href="{{route('book.create')}}"><span class="icon text-white-50"><i class="fas fa-plus"></i>
                                    </span>
                                <span class="text"> Add </span></a>

                        </div>

                    </div> {{-- end  row--}}

                </form> {{-- end form --}}

            </div>

            <div class="card-body">


                <div class="table-responsive text-nowrap">
                    @if(isset($books)&&count($books))
                    <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Book Name</th>
                            <th>Photo</th>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Roof</th>
                            <th>Student Borrow</th>
                            <th>Edit</th>
                            <th>Delete</th>
                            <th>In Roof</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>

                            @foreach($books as $index=> $book)

                            <td>{{$index +1 }}</td>
                            <td>{{$book ->name}}</td>
                            <td><img src="{{$book ->photo}}" style="width: 100px;height: 100px" alt=""></td>
                                <td>{{$book ->title}}</td>
                                <td>{{$book ->description}}</td>
                                <td>{{$book ->getFound()}}</td>
                                <td>
                                    <a href="{{route('student-borrow',$book->id)}}" class="btn btn-primary btn-circle btn-lg"><i class="fas fa-eye"></i></a>
                                </td>
                                <td>
                                    <a href="{{route('book.edit',$book->id)}}" class="btn btn-primary btn-circle btn-lg"><i class="fas fa-info-circle"></i></a>
                                </td>
                                <td>
                                    <form action="{{route('book.destroy',$book->id)}}" method="post" >
                                        {{csrf_field()}}
                                        {{method_field('delete')}}

                                        <button type="submit" class="btn btn-danger btn-circle btn-lg"> <i class="fas fa-trash"></i>
                                        </button>
                                    </form>

                                </td>
                                <td>
                                    <a href="{{route('book.status',$book->id)}}" class="btn btn-success btn-circle btn-lg">@if($book->found==1)<i class="fas fa-check"></i>@else <i class="fas fa-times"></i> @endif </a>
                                </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                    @else
                        <h2>data not found</h2>
                    @endif
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/admin/book/showStudentReq.blade.php
@extends('layouts.admin')

@section('content')

    <div class="container-fluid">

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">  Books <small style="color:black;"></small></h6>  <br>
                @include('admin.include.alerts.errors')
                @include('admin.include.alerts.success')

            </div>

            <div class="card-body">


                <div class="table-responsive text-nowrap">
                    @if(isset($books)&&count($books))
                    <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Name Of User</th>
                            <th>Borrow Date</th>
                            <th>Borrowing time (days)</th>
                            <th>Accept</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            @foreach($books as $index=> $book)
                            <td>{{$index +1 }}</td>
                            <td>{{$book ->user_name}}</td>
                                <td>{{$book ->created_at->format('Y-m-d')}}</td>
                                <td> {{(strtotime($book->Too) - strtotime($book ->created_at->format('Y-m-d')))/60/60/24}}</td>
                                <td>{{$book ->getStatus()}}</td>
                        </tr>
                        @endforeach

                        </tbody>
                    </table>
                    @else
                        <h2>data not </h2>
                    @endif
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@endsection