routes/admin.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/ssss', function () {
    return view('welcome');
});
///////////////////////////////////////////Logout Admin ///////////////////////////////////////////
Route::get('logout' ,function (){
    Auth::guard('admin')->logout();
    return redirect()->route('get.admin.login');
} )->name('admin-logout');
/////////////////////////////////////////End logout//////////////////////////////////////////////

Route::group(['namespace'=>'App\Http\Controllers\Admin','middleware'=>'auth:admin','name'=>'.dashboard'],function () {
    Route::group(['prefix'=>'dashboard'],function () {
        Route::get('/', 'DashboardController@index')->name('dashboard.index');
        /////////////////////////////Start Category//////////////////////////////////////
        Route::resource('category', 'CategoryController')->except(['show']);
        /////////////////////////////End Category//////////////////////////////////////

        /////////////////////////////Start Book//////////////////////////////////////
        Route::resource('book', 'BookController')->except(['show']);
        Route::get('/founded/{ID}','BookController@changeStatus')->name('book.status');
        Route::get('studentBorrowBook/{id}', 'BookController@studentRequest')->name('student-borrow');

        /////////////////////////////End Book//////////////////////////////////////
        /////////////////////////////Start Student//////////////////////////////////////
         Route::resource('student', 'StudentController')->except(['show','create','edit','update','story']);
         Route::get('booksRequest/{id}', 'StudentController@bookRequest')->name('books-request');
        /////////////////////////////End Student//////////////////////////////////////
        /////////////////////////////Start Borrow Request/////////////////////////////////////
         Route::resource('borrowRequest', 'BorrowRequestController')->except(['show','create','edit','update','story']);
        Route::get('/accept/{ID}','BorrowRequestController@changeAccept')->name('borrow.accept');
        Route::get('/Roof/{ID}','BorrowRequestController@changeRoof')->name('roof.found');
        /////////////////////////////End BorrowRequest//////////////////////////////////////

        /// //////////////////////////// change pass//////////////////////////////////////
        Route::get('changePassword','ChangePassController@change')->name('admin.change');
        Route::post('changePassword','ChangePassController@updateChange')->name('admin.update.change');
        /// //////////////////////////// End Pass   /////////////////////////////////////

    });



});
Route::group(['namespace'=>'App\Http\Controllers\Admin\Auth','middleware'=>'guest:admin'],function (){
    Route::get('login','LoginController@getLogin')->name('get.admin.login');
    Route::post('login','LoginController@Login')->name('admin.login');

});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('logout' ,function (){
    Auth::logout();
    return redirect()->route('get.front.login');
} )->name('client-logout');

Route::group(['namespace'=>'App\Http\Controllers\Front','middleware'=>'auth:web'],function () {
    Route::get('booksDet', 'MainController@books')->name('books');
    Route::get('detailsBook/{id}', 'MainController@booksDetails')->name('details-books');
    Route::get('borrowRequest/{id}', 'MainController@borrow_request')->name('borrow-request');
    Route::post('pushBorrow', 'MainController@pushBorrow')->name('push-borrow-request');
    Route::get('borrowRequest', 'MainController@student_borrow_request')->name('student-borrow-request');
    Route::get('profile' , 'MainController@getProfile')->name('get.student.profile');
    Route::post('editProfile' , 'MainController@editProfile')->name('edit.student.profile');
    Route::get('getEditPass' , 'MainController@getEdtPass')->name('get.student.EditPass');
    Route::post('editPass' , 'MainController@editPass')->name('edit.student.Pass');
    Route::get('contact' , 'MainController@getContact')->name('contact.me');



});
Route::group(['namespace'=>'App\Http\Controllers\Front'],function (){
    Route::get('logins','LoginController@getClientLogin')->name('get.front.login');
    Route::post('logins','LoginController@Login')->name('front.login');
    Route::get('registers','RegisterController@getClientRegister')->name('get.front.register');
    Route::post('registers','RegisterController@Register')->name('front.register');
    Route::get('/home', 'MainController@home')->name('client-home');
    Route::get('about-us', 'MainController@about')->name('about.us');


});
/*Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');*/

app/Http/Controllers/Admin/StudentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\BorrowRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class StudentController extends Controller
{

    public function index(Request $request)
    {
        $students=User::where(function ($q) use($request){
            if($request->input('search')){
                return $q ->where('name','like','%'.$request->search.'%');
            }})->get();
        return view('admin.student.index',compact('students'));
    }


    public function destroy($id)
    {
       $students=User::findOrFAil($id);
       if(!$students){
           return redirect()->route('student.index')->with(['error' => 'Sorry This item Not Found']);
       }
       /* $photo=Str::after($students->photo,'assests/');
        $photo=base_path('public/assests/'.$photo);
        unlink($photo);*/
        $students->delete();
        return redirect()->route('student.index')->with(['success'=>"Delete Successfully"]);

    }
    public function bookRequest($id){
        $student=User::findOrFail($id);
         $students= $student->borrowRequests;
        return view('admin.student.showBookReq',compact('students'));
    }
}

resources/views/admin/student/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="container-fluid">

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">  Students <small style="color:black;">{{$students -> count()}}</small></h6>  <br>
                @include('admin.include.alerts.errors')
                @include('admin.include.alerts.success')
                <form action="" method="get">
                    @csrf
                    <div class="row">
                        <div class="col-md-4">
                            <input type="text" name="search" class="form-control" placeholder="search" value="" >
                        </div>
                        <div class="col-md-4">
                            <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i> search</button>
                        </div>

                    </div> {{-- end  row--}}

                </form> {{-- end form --}}

            </div>

            <div class="card-body">


                <div class="table-responsive">
                    @if(isset($students)&&count($students))
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Address</th>
                            <th>Date Of Barth</th>
                            <th>Borrow Request</th>
                            <th>Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            @foreach($students as $index=> $student)

                            <td>{{$index +1 }}</td>
                            <td>{{$student ->name}}</td>
                            <td>{{$student ->email}}</td>
                            <td>{{$student ->address}}</td>
                            <td>{{$student ->dop}}</td>
                            <td>
                                <a href="{{route('books-request',$student ->id)}}" class="btn btn-primary btn-circle btn-lg"> <i class="fas fa-eye"></i>  </a>
                            </td>
                                <td>

                                    <form action="{{route('student.destroy',$student->id)}}" method="post" >
                                        {{csrf_field()}}
                                        {{method_field('delete')}}

                                        <button type="submit" class="btn btn-danger btn-circle btn-lg"> <i class="fas fa-trash"></i>
                                        </button>
                                    </form>

                                </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                    @else
                        <h2>data not found</h2>
                    @endif
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/admin/student/showBookReq.blade.php
@extends('layouts.admin')

@section('content')

    <div class="container-fluid">

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">  Books <small style="color:black;"></small></h6>  <br>
                @include('admin.include.alerts.errors')
                @include('admin.include.alerts.success')

            </div>

            <div class="card-body">


                <div class="table-responsive text-nowrap">
                    @if(isset($students)&&count($students))
                    <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Name Of Book</th>
                            <th>Borrow Date</th>
                            <th>Borrowing time (days)</th>
                            <th>Accept</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            @foreach($students as $index=> $student)
                            <td>{{$index +1 }}</td>
                            <td>{{$student ->book_name}}</td>
                                <td>{{$student ->created_at->format('Y-m-d')}}</td>
                                <td> {{(strtotime($student->Too) - strtotime($student ->created_at->format('Y-m-d')))/60/60/24}}</td>

                                <td>{{$student ->getStatus()}}</td>
                        </tr>
                        @endforeach

                        </tbody>
                    </table>
                    @else
                        <h2>data not found</h2>
                    @endif
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@endsection